# hello world github action yaml file

name: workflow

  on:
    push:
      branch:
        - main
  on:
    pull_request:
      branch:
        - main
  workflow_dispatch:

jobs:
  hello:
    runs-on: ubuntu-latest
    step:
      - uses: actions/checkout@v2
      - name: hello world
      run: echo "hello world testing 321"
      shell: bash

  goodbye:
    runs-on: ubuntu-latest
    step:
      - name: goodbye world
      run: echo "goodbye world testing 123"
      shell: bash

      
